ficus.fit_range <- function(formula,
                      data,
                      group,
                      shared,
                      start,
                      lower_bounds,
                      upper_bounds,
                      resolution,
                      objfun = deviance,
                      FUN = nls,
                      ...) {
  ficus.fit_recursive(formula=formula,
                      data=data,
                      group=group,
                      shared=shared,
                      start=start,
                      lower_bounds=lower_bounds,
                      upper_bounds=upper_bounds,
                      resolution=resolution,
                      recursions=1,
                      reduction=1,
                      objfun=objfun,
                      FUN=FUN,
                      ...)
}
